- hosts: caroller
  gather_facts: no
  vars:
    speech: |
        Jingle Bells!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: caroller
  gather_facts: no
  vars:
    speech: |
        Jingle Bells!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: caroller
  gather_facts: no
  vars:
    speech: |
        Jingle all the way!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"

- hosts: caroller
  gather_facts: no
  vars:
    speech: |
        Oh, what fun it is to ride in a one horse open sleigh!
  tasks:
    - osx_say: voice="{{voice}}" msg="{{speech}}"
